-- Auto-generated by scripts/gen-backdrop-palettes.py
-- Do not edit manually. Re-run after adding/removing backdrops.

local palettes = {
   ["【哲风壁纸】传统水墨-国风山水.png"] = {
      bg = "#0b1419",
      fg = "#f4f1ea",
      dim = "#b1c0c4",
      accent = "#4c91b2",
      accent2 = "#c7508d",
      accent3 = "#b2c355",
      warm = "#d6a541",
      alert = "#de4861",
      border = "#244962",
   },
   ["【哲风壁纸】写意意境-古建写意.png"] = {
      bg = "#101417",
      fg = "#ede8df",
      dim = "#ccbdab",
      accent = "#e15e1d",
      accent2 = "#50c78c",
      accent3 = "#6755c3",
      warm = "#f79b34",
      alert = "#e15e1d",
      border = "#394954",
   },
   ["【哲风壁纸】叶子-水墨.png"] = {
      bg = "#04090b",
      fg = "#d2c5ac",
      dim = "#cec2ad",
      accent = "#b28d4d",
      accent2 = "#4ba8a8",
      accent3 = "#4fa555",
      warm = "#b98f46",
      alert = "#de4861",
      border = "#163a47",
   },
   ["【哲风壁纸】国风插画-国风水墨.png"] = {
      bg = "#0f1410",
      fg = "#edeee9",
      dim = "#afbcb4",
      accent = "#4cb26b",
      accent2 = "#7db55a",
      accent3 = "#c36455",
      warm = "#d6a541",
      alert = "#de4861",
      border = "#384e3d",
   },
}

return palettes
