#!/bin/bash

DPI=$(xrdb -query 2>/dev/null | awk '/Xft.dpi/ {print $2}')

if [ -z "$DPI" ]; then
    echo normal
elif [ "$DPI" -ge 192 ]; then
    echo retina
elif [ "$DPI" -ge 144 ]; then
    echo hidpi
else
    echo normal
fi
