#!/bin/sh

lock=" Lock"
logout=" Logout"
suspend=" Suspend"
reboot=" Reboot"
shutdown=" Shutdown"

confirm() {
    echo -e "Yes\nNo" | rofi -dmenu -i -p "Confirm $1?" \
        -theme ~/.config/rofi/powermenu.rasi -no-custom -selected-row 1
}

chosen=$(printf "%s\n%s\n%s\n%s\n%s\n" "$lock" "$logout" "$suspend" "$reboot" "$shutdown" \
    | rofi -dmenu -i -p "Power" -theme ~/.config/rofi/powermenu.rasi -no-custom)

case "$chosen" in
    "$lock")    i3lock ;;
    "$logout")  i3-msg exit ;;
    "$suspend") systemctl suspend ;;
    "$reboot")
        [ "$(confirm Reboot)" = "Yes" ] && systemctl reboot ;;
    "$shutdown")
        [ "$(confirm Shutdown)" = "Yes" ] && systemctl poweroff ;;
esac
