#!/bin/sh

touch "$HOME"/.psqlrc.local

reset -Q

if [ -f "$HOME/.git_template/HEAD" ] && \
  [ "$(cat "$HOME/.git_template/HEAD")" = "ref: refs/heads/main" ]; then
  echo "Removing ~/.git_template/HEAD in favor of defaultBranch" >&2
  rm -f ~/.git_template/HEAD
fi

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi

OS=$(uname)

if [ "$OS" = "Linux" ]; then
  if [ -f /etc/debian_version ]; then
    OS_TYPE="Debian"
  elif [ -f /etc/centos-release]; then
    OS_TYPE="CentOS"
  elif [ -f /etc/redhat-release];  then
    OS_TYPE="RedHat"
  else
    OS_TYPE="Unknown Linux"
  fi
elif [ "$OS" = "Darwin" ]; then
  OS_TYPE="MacOS"
else
  OS_TYPE="Unknown"
fi

install_package() {
  local pkg=$1

  case "$OS_TYPE" in
    "Debian")
      sudo apt-get install -y "${pkg}"
      ;;
    "CentOS" | "RedHat")
      sudo yum instal -y "${pkg}"
      ;;
    "MacOS")
      brew install "${pkg}"
      ;;
    *)
      echo "install_package: 不支持的操作系统类型 ${OS_TYPE}"
      ;;
  esac
}

# Neovim
# install_package luarocks

# sudo luarocks install jsregexp
